using namespace std;
int cat(int l,int r){return l*10+r;}
char tochar(char* t){return t[0];}
#define scoperes ::
#define inc ++
#define dec --
#define leftpar (
#define rightpar )
#define leftbracket [
#define rightbracket ]
#define leftbrace {
#define rightbrace }
#define leftangle  <
#define rightangle >
#define dot .
#define arrow ->
#define dotp .*
#define arrowp ->*
#define ref &
#define pos +
#define neg -
#define mul *
#define div /
#define mod %
#define lefts <<
#define rigths >>
#define le <=
#define ge >=
#define eq ==
#define ne !=
#define powerop ^
#define pipe |
#define assign =
#define question ?
#define colon :
#define semicolon ;
#define comma ,
#define booleanand &&
#define booleanor ||
#define bitwiseor |
#define zero 0
#define one 1
#define two 2
#define three 3
#define four 4
#define five 5
#define six 6
#define seven 7
#define eight 8
#define nine 9
#define strback "`"
#define capback "~"
#define strone "1"
#define capone "!"
#define strtwo "2"
#define captwo "@"
#define strthree "3"
#define capthree "#"
#define strfour "4"
#define capfour "$"
#define strfive "5"
#define capfive "%"
#define strsix "6"
#define capsix "^"
#define strseven "7"
#define capseven "&"
#define streight "8"
#define capeight "*"
#define strnine "9"
#define capnine "("
#define strzero "0"
#define capzero ")"
#define strneg "-"
#define capneg "_"
#define streq "="
#define capeq "+"
#define strq "q"
#define capq "Q"
#define strw "w"
#define capw "W"
#define stre "e"
#define cape "E"
#define strr "r"
#define capr "R"
#define strt "t"
#define capt "T"
#define stry "y"
#define capy "Y"
#define stru "u"
#define capu "U"
#define stri "i"
#define capi "I"
#define stro "o"
#define capo "O"
#define strp "p"
#define capp "P"
#define strlbr "["
#define caplbr "{"
#define caprbr "}"
#define strrbr "]"
#define strbsh "\\"
#define capbsh "|"
#define stra "a"
#define capa "A"
#define strs "s"
#define caps "S"
#define strd "d"
#define capd "D"
#define strf "f"
#define capf "F"
#define strg "g"
#define capg "G"
#define strh "h"
#define caph "H"
#define strj "j"
#define capj "J"
#define strk "k"
#define capk "K"
#define strl "l"
#define capl "L"
#define strsemi ";"
#define capsemi ":"
#define strquo "'"
#define capquo "\""
#define strz "z"
#define capz "Z"
#define strx "x"
#define capx "X"
#define strc "c"
#define capc "C"
#define strv "v"
#define capv "V"
#define strb "b"
#define capb "B"
#define strn "n"
#define capn "N"
#define strm "m"
#define capm "M"
#define strcom ","
#define capcom "<"
#define strdot "."
#define capdot ">"
#define strslash "/"
#define capslash "?"
#define newline "\n"
#define newrine "\r"
#define tab "\t"
#define space " "
