//Some of this C is from C++, so..
int cat(int l,int r){return l*10+r;}
char tochar(char* t){return t[0];}
#define scoperes ::
#define inc ++
#define dec --
#define leftpar (
#define rightpar )
#define leftbracket [
#define rightbracket ]
#define leftbrace {
#define rightbrace }
#define leftangle  <
#define rightangle >
#define dot .
#define arrow ->
#define dotp .*
#define arrowp ->*
#define ref &
#define pos +
#define neg -
#define mul *
#define div /
#define mod %
#define lefts <<
#define rigths >>
#define le <=
#define ge >=
#define eq ==
#define ne !=
#define powerop ^
#define pipe |
#define assign =
#define question ?
#define colon :
#define semicolon ;
#define comma ,
#define booleanand &&
#define booleanor ||
#define bitwiseor |
#define zero 0
#define one 1
#define two 2
#define three 3
#define four 4
#define five 5
#define six 6
#define seven 7
#define eight 8
#define nine 9
#define strback "`"
#define strtilde "~"
#define strone "1"
#define strexc "!"
#define strtwo "2"
#define strat "@"
#define strthree "3"
#define strhash "#"
#define strfour "4"
#define strmoney "$"
#define strfive "5"
#define strmod "%"
#define strsix "6"
#define strpow "^"
#define strseven "7"
#define strand "&"
#define streight "8"
#define strmul "*"
#define strnine "9"
#define strleftpar "("
#define strzero "0"
#define strrightpar ")"
#define strneg "-"
#define strundsco "_"
#define streq "="
#define strpos "+"
#define strq "q"
#define capq "Q"
#define strw "w"
#define capw "W"
#define stre "e"
#define cape "E"
#define strr "r"
#define capr "R"
#define strt "t"
#define capt "T"
#define stry "y"
#define capy "Y"
#define stru "u"
#define capu "U"
#define stri "i"
#define capi "I"
#define stro "o"
#define capo "O"
#define strp "p"
#define capp "P"
#define strlbr "["
#define caplbr "{"
#define caprbr "}"
#define strrbr "]"
#define strbsh "\\"
#define capbsh "|"
